---
- name: Deploy webserver
  hosts: webservers
  serial: 1
  become: yes
  roles:
    - ansistrano.deploy
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/"
    ansistrano_deploy_to: "/home/vagrant/application"
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: git
    ansistrano_git_repo: https://github.com/hexlet-components/devops-example-app.git
    ansistrano_git_branch: main
    ansistrano_git_depth: 1
    ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/deploy_webservers/before_setup.yml"
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/deploy_webservers/after_update_code.yml"
    ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/deploy_webservers/after_cleanup.yml"
  tasks: []
