---
- name: setup webserver
  become: yes
  hosts: webservers
  vars:
    nodejs_version: "14.x"
  roles:
    - name: geerlingguy.nodejs
  tasks:
    - name: Install system dependencies
      apt:
        update_cache: yes
        name:
          - tree
          - git
          - make

    - name: "Install forever (to run Node.js app)."
      npm:
        name: forever
        global: yes
        state: present
